### ISSUE TITLE
Incident type

### ISSUE THREAD

**Issue by alanytran** [info442-spr22/e-team#14]
Will create checkboxes for each incident type so users can easily check it to notify others

**Comment by Yueemxn** [comment]
I changed the naming of some incident type. Currently I'm using react form to create the checkbox due to limited time, but in next sprint I'll use react-bootstrap.

**Comment by Yueemxn** [comment]
I changed the naming of some incident type. Currently I'm using react form to create the checkbox due to limited time, but in next sprint I'll use react-bootstrap.
