### ISSUE TITLE
no crime labeled on map. minor 

### ISSUE THREAD

**Issue by hadardolev** [info442-spr22/e-team#52]

**Comment by hadardolev** [comment]
(Sorry I accidentally exited out while I was writing this) But When I submit a crime it doesn't show up on the map. I'm not sure if this was a feature or not though.

**Comment by alanytran** [comment]
We will try to have something show up on the map when users type in a report.

**Comment by Yueemxn** [comment]
Implemented props.location.state and local storage to pass the report data to the homepage so the reports can render as color-coded markers according to the incident type.
