### ISSUE TITLE
(Minor)After submitting a crime, I don't see anything populating on the main page or the profile page. 

### ISSUE THREAD

**Issue by victorgmaciel** [info442-spr22/e-team#53]
Bug.

**Comment by jeannechoi00** [comment]
To add on: 
**Summary of the problem:** 
- When submitting a crime the map or main page does not drop a pin or represent this crime in any sort of way. 
**Encountered in** Chrome v90.0.4430.85 on macOS Catalina
steps to reproduce
expected result: crimes submitted in form are produced and pinned on the visual map
actual result: Map stays static

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/52
