### ISSUE TITLE
Attempted using mobile app to see media query and receive error about accessibility (Major) (Bug)

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/e-team#54]
I get the error "Unable to process request due to initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared". I can't access the web app through my mobile device

Environment encountered in: Chrome on MacOs
steps to reproduce: Add in media queries/debug error to make accessible on mobile device
expected result: Loaded webpage
actual result: Error message

**Comment by alanytran** [comment]
Map works on most devices already
