### ISSUE TITLE
(Minor bug) Nav bar links are displayed with list dots and vertically

### ISSUE THREAD

**Issue by fretws** [info442-spr22/e-team#56]
The nav bar links, should not have the \<ul> dots showing, and should be formatted horizontally
Steps to recreate: Log in with google
Expected result: The nav links to have no list dots and be formatted horizontally
Actualy result: they have the dots and are stacked on top of each other

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/55
