### ISSUE TITLE
Navbar Styling of Coloring (Home and Profile Links) Feature Request (“Enhancement”)

### ISSUE THREAD

**Issue by nihagaddam** [info442-spr22/e-team#58]
Add Styling to Home and Profile Links in the Navbar to correlate more with styling of Logout button. This would be useful for the user because it is hard to see the current links: once you click on the links, they turn purple, thus are hard to see against the purple navbar.

**Comment by pranavshekar** [comment]
Additional Info: Adding on to this styling tip, I would get rid of the bulleted list in the navbar. Currently, it looks like 'Home,' 'Profile,' and 'Logout' are stacked on top of each other and I think this UX is a bit hard to understand. It also looks like a bug even though it technically isn't. I would also agree with Niha and change the coloring

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/55
