### ISSUE TITLE
(Minor, Enhancement) Secure U District title doesn't return to home

### ISSUE THREAD

**Issue by spudists** [info442-spr22/e-team#60]
Clicking the title of the web page doesn't return to home.  Usually it is intuitive to click the icon or header to return to home
HP Pavilion, Chrome
Enter one of the sub-pages and click on the site name, no action takes place.
Expected to return to home when clicking on Secure U District

**Comment by alanytran** [comment]
We have the home button to return to the main page already. We also have a return to map page (which is also the home page)
