### ISSUE TITLE
(Minor) Two 'Incident Type' inputs

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/e-team#62]
There are two 'Select Incident Type' inputs. Confusing how they are different from each other and seems like a mistake.

Severity: minor
Environment: Chrome v101.0.4951.67 on Windows
expected result: only one input for 'Select Incident Type' 
actual result: two input 'Select Incident Type'

**Comment by alanytran** [comment]
We will get rid of one of the inputs, or give a clear difference between the two. Due 5/29

**Comment by Yueemxn** [comment]
Fixed the typo on the form page
