### ISSUE TITLE
(Minor) No user feedback for submitting the report

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/e-team#64]
I am not sure if my report got submitted and where I could see it on the map.

Severity: minor
Environment: Chrome v101.0.4951.67 on Windows
expected result: seeing some form of user feedback after submitting the report
actual result: redirects the page to the main

**Comment by alanytran** [comment]
We will add this feature after someone hits the submit button. Due 5/29

**Comment by Yueemxn** [comment]
Added an alert message indicating the user has submitted their form successfully when they submit a form.
