### ISSUE TITLE
Bug: Can submit empty incident forms

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/e-team#66]
Severity: minor
Summary: Users are able to submit empty incident forms
Environment: Google Chrome Version 101.0.4951.67, Windows 10
Steps to reproduce: Click on 'Report an incident button', and click submit without entering anything
Expected Result: A warning the form is empty or some other way preventing the form from being submitted.
Actual Result: The form being submitted.

**Comment by alanytran** [comment]
We will put more restrictions so that users will not be able to submit empty forms. due 5/29

**Comment by Yueemxn** [comment]
Added form validation so the users can't submit report forms unless they fill out every section.
