### ISSUE TITLE
(enhancement) a different page for the map so user can use whole screen. 

### ISSUE THREAD

**Issue by victorgmaciel** [info442-spr22/e-team#68]
**● Description of the requested feature**
When the user clicks the `Map` option on the navbar, there is no rerouting to a page with just the map. 

**● Explanation of why it would be useful**
As a user, I might benefit from having the whole screen in order to visualize the bike path I want to take.

**Comment by alanytran** [comment]
Good point, but I think our team wants to go in the direction of having the map on the same page as other features
