### ISSUE TITLE
BUG: Cannot zoom in or out on map

### ISSUE THREAD

**Issue by cavazd** [info442-spr22/e-team#72]
**Minor Bug**

* Summary: I attempted to use my trackpad to zoom in and out on the map and it seems to do it a little bit but not a lot. My laptop has a touch screen and using that worked though.
* Environment: Firefox 100.0.1 on Windows11
* Steps to reproduce: Sign in with google. Using a trackpad try to zoom in and out by pinching and the opposite of pinching.
* Expected results: Map will zoom in and out based on my motions
* Actual result: Map will either not move at all or will move *very* slightly

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/67
