### ISSUE TITLE
[Enhancement] Adding instructions or summary of app's purpose

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/e-team#77]
Upon first entering this site and not reading anything, there is just a big map, and the things that stand out on the map the most are restaurants. If I entered this app without reading the readme, I would think this is an app for helping find restaurants, so I think it would be helpful to have a summary of the app/about section at the top of the home page.

**Comment by alanytran** [comment]
We will add a summary above the map about the purpose

**Comment by Yueemxn** [comment]
Summary added
