### ISSUE TITLE
Report Incident Map Confirm Button Does not Work (Major Bug)

### ISSUE THREAD

**Issue by nihagaddam** [info442-spr22/e-team#79]
Summary: When Searching for a Location on the Report Incident Page Map and Clicking the Confirm Button causes the website to not render.
Environment: MacBook Air, Chrome, iPhone 13, Safari
Steps to reproduce: Click on Report an Incident Button, Use Search Bar in Map to find a location, click on Confirm button (no feedback), clicks on button again, page crashes.
Expected result: Should be able to confirm the location selected on the map by clicking on the Confirm button.
Actual result: Location is not confirmed after pressing the Confirm button once, and page crashes after pressing button twice.

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/52
