### ISSUE TITLE
Enhancement: Change color of links on navbar

### ISSUE THREAD

**Issue by RachelChung2020** [info442-spr22/e-team#81]
The purple text on the purple background for "Home" and "Profile" on the navbar is a bit difficult to read. Also the logout button is a lot larger and more noticeable, so it is kind of harder to click on Home or Profile, so maybe add more spacing between the logout button and the other links? This might be helpful for improving accessibility and user experience. Great work!

**Comment by alanytran** [comment]
https://github.com/info442-spr22/e-team/issues/55
