### ISSUE TITLE
Minor bug: Long and Lat form input don't work

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/e-team#82]
When I try to type in numbers for the coordinates, nothing changes. It won't let me input numbers.

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce:

1. On home page, click "report an incident"
2. Click on Lat or Long input form
3. Type any number

Expected result: long and lat forms allow users to change numbers

Actual result: no change, long and lat forms still remain 0

<img width="263" alt="Screen Shot 2022-05-18 at 10 55 18 AM" src="https://user-images.githubusercontent.com/70997571/169110454-bceca2fe-c490-458b-9272-d331717de6fe.png">

**Comment by sharlenef** [comment]
Got it to work at the end, but I still think it would be good if users can freely type in the coordinates or give them clearer instructions on how to fill in these inputs

**Comment by alanytran** [comment]
You have to type in the address, then the lat and long will show up. We will make this more clear with instructions
