### ISSUE TITLE
Minor Bug: The size of the map has block the options in the page

### ISSUE THREAD

**Issue by LouisXO** [info442-spr22/e-team#84]
As a user, I could only see the map on the website, it blocked everything, if I did not accidentally scroll down, I would not able to see the "report an incident". This button compared with the map is too small.

Chrome Version 101.0.4951.64 (Official Build) (arm64)
macOS Monterey

**Comment by MARY4177** [comment]
We would add some texts on the home page to explain the app, and the confusion of having to scroll down will automatically be solved.
